echo init submodule...
git submodule init

echo update submodule...
git submodule update

echo copy source to root folder...
xcopy ".\src\comn\.root" ".\" /E /Y

echo copy source to src folder...
xcopy ".\src\comn\.src" ".\src" /E /Y

echo node package manager install...
npm install

